[package]
name = "julia_set"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.13.0"
winit = "0.28"
winit_input_helper = "0.14"
env_logger = "0.10"
log = "0.4"
colorgrad = "0.6.2"
